# Generated by Django 6.0.5 on 2026-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_biblioteca', models.CharField(default='Sistema Biblioteca', max_length=200)),
                ('dias_prestamo', models.IntegerField(default=14)),
                ('multa_por_dia', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
